blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ è®¨è®ºåŒº
    url: https://github.com/DyroS3/dy_job_quick_chat/discussions
    about: æœ‰é—®é¢˜æƒ³è®¨è®ºï¼Ÿä½¿ç”¨è®¨è®ºåŒºè€Œä¸æ˜¯ Issue
  - name: ğŸ“– æ–‡æ¡£
    url: https://github.com/DyroS3/dy_job_quick_chat#readme
    about: å…ˆæŸ¥çœ‹æ–‡æ¡£ï¼Œä¹Ÿè®¸èƒ½æ‰¾åˆ°ç­”æ¡ˆ
